### ISSUE TITLE
Implement Install Script

### ISSUE THREAD

**Issue by richardcase** [90poe/connectctl#18]
**Describe the solution you'd like**
Support installation via script. Like [golangci-lint](https://github.com/golangci/golangci-lint#ci-installation):

```bash
curl -sfL https://install.goreleaser.com/github.com/90poe/connectctl.sh | sh -s -- -b $(go env GOPATH)/bin vX.Y.Z
```

**Comment by ahmedsharif865** [comment]
Is someone still working on this issue?

**Comment by richardcase** [comment]
@ahmedsharif865 -  Its no currently assigned to anyone. Would you like to work on it?

**Comment by richardcase** [comment]
This ticket was about providing a means to install `connectctl` using curl like golangci-lint does. Its worth looking at https://install.goreleaser.com/
