### ISSUE TITLE
Cluster address should be an argument at the `connectors` level

### ISSUE THREAD

**Issue by the4thamigo-uk** [90poe/connectctl#36]
Users of the command cannot conveniently call multiple invocations of the cli tool using different sub-commands of `connectctl connectors` 

It would be more convenient to put common cli arguments at the level of connectors, e.g. 

```
connectctl connectors -c http://myserver list
```

This would make it easy to `ctrl-k` the sub command in the terminal to delete the sub-command and its arguments, also it would enable the user to more easily use `alias` to make a connectctl for a particular cluster for example.

**Comment by mdevilliers** [comment]
I think that ./connectctl works as described -  

``` ./connectctl connectors list -c http://0.0.0.0:8083
INFO[2019-10-11T10:36:04+01:00] connectctl, a Kafka Connect CLI
[
...
]%
./connectctl connectors -c http://0.0.0.0:8083 list
INFO[2019-10-11T10:36:15+01:00] connectctl, a Kafka Connect CLI
[
...
 }
]%
./connectctl -c http://0.0.0.0:8083 connectors list
INFO[2019-10-11T10:37:09+01:00] connectctl, a Kafka Connect CLI
[
...
 }
]%'

Can someone confirm?
